# Generated by Django 6.0.7 on 2026-07-17 05:22

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(default=core.models.generate_parcel_id, editable=False, max_length=20, unique=True)),
                ('owner_name', models.CharField(max_length=200)),
                ('owner_phone', models.CharField(blank=True, max_length=30)),
                ('zone', models.CharField(help_text='e.g. Bastos, Yaounde', max_length=200)),
                ('size_sqm', models.FloatField(help_text='Approximate size in square meters')),
                ('boundary', models.JSONField(help_text='List of [lat, lng] points forming the parcel boundary')),
                ('status', models.CharField(choices=[('active', 'Active - no conflicts'), ('flagged', 'Flagged - overlapping claim'), ('disputed', 'Disputed - report filed')], default='active', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_parcels', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(max_length=200)),
                ('reporter_contact', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='core.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='OverlapFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overlap_area_sqm', models.FloatField()),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('parcel_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_as_a', to='core.parcel')),
                ('parcel_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overlaps_as_b', to='core.parcel')),
            ],
            options={
                'unique_together': {('parcel_a', 'parcel_b')},
            },
        ),
    ]
