# Generated by Django 6.0.7 on 2026-07-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parcel_asking_price_parcel_for_sale_parcel_listed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_index', models.PositiveIntegerField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField(default=dict)),
                ('previous_hash', models.CharField(max_length=64)),
                ('hash', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['block_index'],
            },
        ),
    ]
