# Generated by Django 6.0.7 on 2026-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auditblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditblock',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
