# Generated by Django 6.0.7 on 2026-07-28 17:30

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_auditblock_timestamp'),
    ]

    operations = [
        # Indexes on frequently queried fields for better performance
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['zone'], name='parcel_zone_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['status'], name='parcel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['for_sale'], name='parcel_for_sale_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['-registered_at'], name='parcel_registered_at_idx'),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(fields=['-listed_at'], name='parcel_listed_at_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contract_status_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['-created_at'], name='contract_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['buyer'], name='contract_buyer_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['seller'], name='contract_seller_idx'),
        ),
        migrations.AddIndex(
            model_name='disputereport',
            index=models.Index(fields=['parcel'], name='dispute_parcel_idx'),
        ),
        migrations.AddIndex(
            model_name='disputereport',
            index=models.Index(fields=['resolved'], name='dispute_resolved_idx'),
        ),
        # Composite indexes for common query patterns
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(
                fields=['-listed_at', '-registered_at'],
                name='parcel_recent_listings_idx'
            ),
        ),
        migrations.AddIndex(
            model_name='parcel',
            index=models.Index(
                fields=['zone', 'status'],
                name='parcel_zone_status_idx'
            ),
        ),
        # Unique constraint for OverlapFlag (already exists in Meta, just verify)
        # This is already defined in models.py via unique_together
    ]