# Generated by Django 6.0.7 on 2026-07-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputereport',
            name='supporting_document',
            field=models.FileField(blank=True, help_text='Upload supporting evidence', null=True, upload_to='documents/disputes/'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='survey_plan',
            field=models.FileField(blank=True, help_text='Upload the survey plan', null=True, upload_to='documents/survey_plans/'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='title_deed',
            field=models.FileField(blank=True, help_text='Upload the title deed document', null=True, upload_to='documents/title_deeds/'),
        ),
    ]
