# Generated by Django 6.0.7 on 2026-07-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_disputereport_supporting_document_parcel_survey_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Admin-verified seller/notary'),
        ),
    ]
